-- Crear la base de datos
CREATE DATABASE GestionVentas;

-- Crear tabla Clientes
CREATE TABLE Clientes (
    ClienteID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre NVARCHAR2(50),
    Apellido NVARCHAR2(50),
    Email NVARCHAR2(100),
    Telefono NVARCHAR2(20),
    FechaRegistro DATE
);

-- Crear tabla Productos
CREATE TABLE Productos (
    ProductoID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NombreProducto NVARCHAR2(100),
    Categoria NVARCHAR2(50),
    Precio NUMBER(10, 2)
);

-- Crear tabla Ventas
CREATE TABLE Ventas (
    VentaID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FechaVenta DATE,
    ClienteID NUMBER,
    TotalVenta NUMBER(10, 2),
    FOREIGN KEY (ClienteID) REFERENCES Clientes(ClienteID)
);

-- Crear tabla DetallesVentas
CREATE TABLE DetallesVentas (
    DetalleID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VentaID NUMBER,
    ProductoID NUMBER,
    Cantidad NUMBER,
    TotalLinea NUMBER(10, 2),
    FOREIGN KEY (VentaID) REFERENCES Ventas(VentaID),
    FOREIGN KEY (ProductoID) REFERENCES Productos(ProductoID)
);

-- Supongamos que existe una columna de stock en la tabla Productos
ALTER TABLE Productos ADD (Stock NUMBER DEFAULT 10);

-- Insertar datos ficticios en la tabla Clientes
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) VALUES ('Juan', 'Pérez', 'juan.perez@example.com', '123-456-7890', TO_DATE('2023-01-10', 'YYYY-MM-DD'));
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) VALUES ('Ana', 'López', 'ana.lopez@example.com', '987-654-3210', TO_DATE('2022-11-15', 'YYYY-MM-DD'));
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) VALUES ('Carlos', 'García', 'carlos.garcia@example.com', '456-789-0123', TO_DATE('2023-03-20', 'YYYY-MM-DD'));
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) VALUES ('María', 'Hernández', 'maria.hernandez@example.com', '321-654-9870', TO_DATE('2023-02-05', 'YYYY-MM-DD'));
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) VALUES ('Luis', 'Martínez', 'luis.martinez@example.com', '654-321-0987', TO_DATE('2023-01-25', 'YYYY-MM-DD'));
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) VALUES ('Elena', 'Rodríguez', 'elena.rodriguez@example.com', '789-012-3456', TO_DATE('2023-04-10', 'YYYY-MM-DD'));
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) VALUES ('Jorge', 'Sánchez', 'jorge.sanchez@example.com', '890-123-4567', TO_DATE('2022-12-01', 'YYYY-MM-DD'));
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) VALUES ('Lucía', 'Ramírez', 'lucia.ramirez@example.com', '567-890-1234', TO_DATE('2023-05-15', 'YYYY-MM-DD'));
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) VALUES ('Miguel', 'Torres', 'miguel.torres@example.com', '345-678-9012', TO_DATE('2022-10-30', 'YYYY-MM-DD'));
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) VALUES ('Sofía', 'Flores', 'sofia.flores@example.com', '234-567-8901', TO_DATE('2023-02-22', 'YYYY-MM-DD'));
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) VALUES ('Pedro', 'Morales', 'pedro.morales@example.com', '901-234-5678', TO_DATE('2022-09-18', 'YYYY-MM-DD'));
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) VALUES ('Isabel', 'Núñez', 'isabel.nunez@example.com', '123-789-4560', TO_DATE('2023-03-30', 'YYYY-MM-DD'));
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) VALUES ('Andrés', 'Jiménez', 'andres.jimenez@example.com', '345-678-1230', TO_DATE('2023-01-05', 'YYYY-MM-DD'));
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) VALUES ('Marta', 'Ruiz', 'marta.ruiz@example.com', '678-901-2345', TO_DATE('2023-04-18', 'YYYY-MM-DD'));
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) VALUES ('Raúl', 'Díaz', 'raul.diaz@example.com', '456-123-7890', TO_DATE('2023-02-12', 'YYYY-MM-DD'));

-- Insertar datos ficticios en la tabla Productos
INSERT INTO Productos (NombreProducto, Categoria, Precio) VALUES ('Televisor', 'Electrónica', 500.00);
INSERT INTO Productos (NombreProducto, Categoria, Precio) VALUES ('Lavadora', 'Electrodomésticos', 300.00);
INSERT INTO Productos (NombreProducto, Categoria, Precio) VALUES ('Sofá', 'Muebles', 700.00);
INSERT INTO Productos (NombreProducto, Categoria, Precio) VALUES ('Mesa', 'Muebles', 150.00);
INSERT INTO Productos (NombreProducto, Categoria, Precio) VALUES ('Cafetera', 'Electrodomésticos', 80.00);
INSERT INTO Productos (NombreProducto, Categoria, Precio) VALUES ('Smartphone', 'Electrónica', 600.00);
INSERT INTO Productos (NombreProducto, Categoria, Precio) VALUES ('Microondas', 'Electrodomésticos', 120.00);
INSERT INTO Productos (NombreProducto, Categoria, Precio) VALUES ('Cama', 'Muebles', 400.00);
INSERT INTO Productos (NombreProducto, Categoria, Precio) VALUES ('Refrigerador', 'Electrodomésticos', 1000.00);
INSERT INTO Productos (NombreProducto, Categoria, Precio) VALUES ('Ventilador', 'Electrodomésticos', 50.00);
INSERT INTO Productos (NombreProducto, Categoria, Precio) VALUES ('Ordenador', 'Electrónica', 800.00);
INSERT INTO Productos (NombreProducto, Categoria, Precio) VALUES ('Lámpara', 'Muebles', 40.00);
INSERT INTO Productos (NombreProducto, Categoria, Precio) VALUES ('Bicicleta', 'Deportes', 200.00);
INSERT INTO Productos (NombreProducto, Categoria, Precio) VALUES ('Tablet', 'Electrónica', 300.00);
INSERT INTO Productos (NombreProducto, Categoria, Precio) VALUES ('Zapatillas', 'Deportes', 100.00);

-- Insertar datos ficticios en la tabla Ventas
INSERT INTO Ventas (FechaVenta, ClienteID, TotalVenta) VALUES (TO_DATE('2023-05-01', 'YYYY-MM-DD'), 1, 700.00);
INSERT INTO Ventas (FechaVenta, ClienteID, TotalVenta) VALUES (TO_DATE('2023-04-20', 'YYYY-MM-DD'), 2, 300.00);
INSERT INTO Ventas (FechaVenta, ClienteID, TotalVenta) VALUES (TO_DATE('2023-05-05', 'YYYY-MM-DD'), 3, 1200.00);
INSERT INTO Ventas (FechaVenta, ClienteID, TotalVenta) VALUES (TO_DATE('2023-04-15', 'YYYY-MM-DD'), 4, 500.00);
INSERT INTO Ventas (FechaVenta, ClienteID, TotalVenta) VALUES (TO_DATE('2023-03-10', 'YYYY-MM-DD'), 5, 1300.00);
INSERT INTO Ventas (FechaVenta, ClienteID, TotalVenta) VALUES (TO_DATE('2023-02-25', 'YYYY-MM-DD'), 6, 450.00);
INSERT INTO Ventas (FechaVenta, ClienteID, TotalVenta) VALUES (TO_DATE('2023-01-10', 'YYYY-MM-DD'), 7, 600.00);
INSERT INTO Ventas (FechaVenta, ClienteID, TotalVenta) VALUES (TO_DATE('2023-01-15', 'YYYY-MM-DD'), 8, 800.00);
INSERT INTO Ventas (FechaVenta, ClienteID, TotalVenta) VALUES (TO_DATE('2023-04-01', 'YYYY-MM-DD'), 9, 900.00);
INSERT INTO Ventas (FechaVenta, ClienteID, TotalVenta) VALUES (TO_DATE('2023-02-10', 'YYYY-MM-DD'), 10, 200.00);
INSERT INTO Ventas (FechaVenta, ClienteID, TotalVenta) VALUES (TO_DATE('2023-03-05', 'YYYY-MM-DD'), 11, 750.00);
INSERT INTO Ventas (FechaVenta, ClienteID, TotalVenta) VALUES (TO_DATE('2023-05-12', 'YYYY-MM-DD'), 12, 1000.00);
INSERT INTO Ventas (FechaVenta, ClienteID, TotalVenta) VALUES (TO_DATE('2023-04-08', 'YYYY-MM-DD'), 13, 650.00);
INSERT INTO Ventas (FechaVenta, ClienteID, TotalVenta) VALUES (TO_DATE('2023-03-20', 'YYYY-MM-DD'), 14, 950.00);
INSERT INTO Ventas (FechaVenta, ClienteID, TotalVenta) VALUES (TO_DATE('2023-04-18', 'YYYY-MM-DD'), 15, 1100.00);

-- Crear tabla de auditoría para registrar el total de ventas por cliente
CREATE TABLE ClientesAuditoria (
    AuditoriaID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClienteID NUMBER,
    TotalVentas NUMBER(10, 2)
);

