-- Crear tabla Clientes
CREATE TABLE Clientes (
    ClienteID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(50),
    Apellido VARCHAR2(50),
    Email VARCHAR2(100),
    Telefono VARCHAR2(20),
    FechaRegistro DATE
);

-- Crear tabla Productos
CREATE TABLE Productos (
    ProductoID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NombreProducto VARCHAR2(100),
    Precio NUMBER(10, 2),
    Stock NUMBER
);

-- Crear tabla Ventas
CREATE TABLE Ventas (
    VentaID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClienteID NUMBER,
    FechaVenta DATE,
    TotalVenta NUMBER(10, 2),
    FOREIGN KEY (ClienteID) REFERENCES Clientes(ClienteID)
);

-- Crear tabla DetallesVentas
CREATE TABLE DetallesVentas (
    DetalleID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VentaID NUMBER,
    ProductoID NUMBER,
    Cantidad NUMBER,
    TotalLinea NUMBER(10, 2),
    FOREIGN KEY (VentaID) REFERENCES Ventas(VentaID),
    FOREIGN KEY (ProductoID) REFERENCES Productos(ProductoID)
);

-- Insertar datos en Clientes
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) 
VALUES ('Juan', 'Pérez', 'juan.perez@example.com', '123456789', SYSDATE);
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) 
VALUES ('Ana', 'López', 'ana.lopez@example.com', '987654321', SYSDATE);
INSERT INTO Clientes (Nombre, Apellido, Email, Telefono, FechaRegistro) 
VALUES ('Carlos', 'Ramírez', 'carlos.ramirez@example.com', '555111222', SYSDATE);

-- Insertar datos en Productos
INSERT INTO Productos (NombreProducto, Precio, Stock) 
VALUES ('Laptop', 1200, 10);
INSERT INTO Productos (NombreProducto, Precio, Stock) 
VALUES ('Smartphone', 800, 15);
INSERT INTO Productos (NombreProducto, Precio, Stock) 
VALUES ('Televisor', 1000, 7);

-- Insertar datos en Ventas
INSERT INTO Ventas (ClienteID, FechaVenta, TotalVenta) 
VALUES (1, SYSDATE, 1200);
INSERT INTO Ventas (ClienteID, FechaVenta, TotalVenta) 
VALUES (2, SYSDATE, 1600);

-- Insertar datos en DetallesVentas
INSERT INTO DetallesVentas (VentaID, ProductoID, Cantidad, TotalLinea) 
VALUES (1, 1, 1, 1200);
INSERT INTO DetallesVentas (VentaID, ProductoID, Cantidad, TotalLinea) 
VALUES (2, 2, 1, 800);
INSERT INTO DetallesVentas (VentaID, ProductoID, Cantidad, TotalLinea) 
VALUES (2, 3, 1, 1000);
